#! /bin/bash

# use:
# testBiolockj exampleTestList.txt
# OR
# testBiolockj exampleTestList.txt collectionOfResults.txt

TESTER_JAR=${SHEP}/MockMain/dist/MockMain.jar
BLJ_JAR=${BLJ}/dist/BioLockJ.jar

# make a horizontal line in the console
echo "=========================================================="

if [ "$#" -eq 1 ]; then
	java -cp ${TESTER_JAR}:${BLJ_JAR} sheepdog.RunMock $1
elif [ "$#" -eq 2 ]; then
	java -cp ${TESTER_JAR}:${BLJ_JAR} sheepdog.RunMock $1 $2
else
	echo "Oh dear.  testBiolockj reqires one argument giving the path to the test list."
	exit 1
fi
