#! /bin/bash

# use:
# testBiolockj exampleTestList.txt
# OR
# testBiolockj exampleTestList.txt collectionOfResults.txt

TESTER_JAR=${SHEP}/MockMain/dist/TestBioLockJ.jar
BLJ_JAR=${BLJ}/dist/BioLockJ.jar

doBuild(){
	echo "======================build BioLockJ======================"
	ant -f ${BLJ}/resources/build.xml
	echo "====================build TestBioLockJ===================="
	ant -f ${SHEP}/MockMain/build.xml
}

if [ "$#" -eq 0 ]; then
	doBuild
elif [ "$#" -eq 1 ]; then
	doBuild
	echo "=========================================================="
	java -cp ${TESTER_JAR}:${BLJ_JAR} sheepdog.TestBioLockJ $1
elif [ "$#" -eq 2 ]; then
	echo "=========================================================="
	java -cp ${TESTER_JAR}:${BLJ_JAR} sheepdog.TestBioLockJ $1 $2
else
	echo "Too many args passed to testBiolockj."
	exit 1
fi
